//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoptrue.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class middle
    {
        public int otderid { get; set; }
        public int prodid { get; set; }
        public int id { get; set; }
    
        public virtual orders orders { get; set; }
        public virtual products products { get; set; }
    }
}
